### PR TITLE
commit

### PR DESCRIPTION
**Pull request by Baiano157**
Vai da certo

### CODE REVIEW

**Comment by Kerimbeys** [comment]
Vai da certo

**Comment by aramsoft89** [comment]
python3 lazymux.py
Traceback (most recent call last):
  File "/root/Lazymux-master/lazymux.py", line 6, in <module>
    from core.lzmcore import *
  File "/root/Lazymux-master/core/lzmcore.py", line 26, in <module>
    cache_1 = prefix+"/tmp/lazymux_1"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by aramsoft89** [comment]
python2 lazymux.py
  File "lazymux.py", line 87
    infogathering += f"{x} "
                           ^
SyntaxError: invalid syntax

**Comment by Gameye98** [comment]
> python2 lazymux.py
>   File "lazymux.py", line 87
>     infogathering += f"{x} "
>                            ^
> SyntaxError: invalid syntax
> 

Always remember to not use python v2 to execute lazymux :)
Its need python 3 to run

$ python --version
Python 3.10.4
$ python lazymux.py

**Comment by aramsoft89** [comment]
┌──(kali㉿kali)-[~/Desktop/Lazymux-master]
└─$ python --version       
Python 3.10.4
_________________________


python3 lazymux.py
Traceback (most recent call last):
  File "/root/Lazymux-master/lazymux.py", line 6, in <module>
    from core.lzmcore import *
  File "/root/Lazymux-master/core/lzmcore.py", line 26, in <module>
    cache_1 = prefix+"/tmp/lazymux_1"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by aramsoft89** [comment]
thanks for help me

**Comment by aramsoft89** [comment]
──(root㉿kali)-[~/Lazymux-master]
└─#  python lazymux.py
Traceback (most recent call last):
  File "/root/Lazymux-master/lazymux.py", line 6, in <module>
    from core.lzmcore import *
  File "/root/Lazymux-master/core/lzmcore.py", line 26, in <module>
    cache_1 = prefix+"/tmp/lazymux_1"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by Gameye98** [comment]
Lazymux only work on termux environment bcuz its need a specific package and some config with only termux had.

Why do u even running Lazymux in fedora? Pls read the README.md

**Comment by aramsoft89** [comment]
ok thanks my bro  im working on the   system kali linux  it must be for him

**Pull request closed without merging**
